package android.support.constraint;

import com.movypark.cordoba.C0220R;

public final class C0002R {

    public static final class attr {
        public static final int layout_constraintBaseline_creator = 2130903174;
        public static final int layout_constraintBaseline_toBaselineOf = 2130903175;
        public static final int layout_constraintBottom_creator = 2130903176;
        public static final int layout_constraintBottom_toBottomOf = 2130903177;
        public static final int layout_constraintBottom_toTopOf = 2130903178;
        public static final int layout_constraintDimensionRatio = 2130903179;
        public static final int layout_constraintEnd_toEndOf = 2130903180;
        public static final int layout_constraintEnd_toStartOf = 2130903181;
        public static final int layout_constraintGuide_begin = 2130903182;
        public static final int layout_constraintGuide_end = 2130903183;
        public static final int layout_constraintGuide_percent = 2130903184;
        public static final int layout_constraintHorizontal_bias = 2130903185;
        public static final int layout_constraintHorizontal_chainPacked = 2130903186;
        public static final int layout_constraintHorizontal_weight = 2130903187;
        public static final int layout_constraintLeft_creator = 2130903188;
        public static final int layout_constraintLeft_toLeftOf = 2130903189;
        public static final int layout_constraintLeft_toRightOf = 2130903190;
        public static final int layout_constraintRight_creator = 2130903191;
        public static final int layout_constraintRight_toLeftOf = 2130903192;
        public static final int layout_constraintRight_toRightOf = 2130903193;
        public static final int layout_constraintStart_toEndOf = 2130903194;
        public static final int layout_constraintStart_toStartOf = 2130903195;
        public static final int layout_constraintTop_creator = 2130903196;
        public static final int layout_constraintTop_toBottomOf = 2130903197;
        public static final int layout_constraintTop_toTopOf = 2130903198;
        public static final int layout_constraintVertical_bias = 2130903199;
        public static final int layout_constraintVertical_chainPacked = 2130903200;
        public static final int layout_constraintVertical_weight = 2130903201;
        public static final int layout_editor_absoluteX = 2130903202;
        public static final int layout_editor_absoluteY = 2130903203;
        public static final int layout_goneMarginBottom = 2130903204;
        public static final int layout_goneMarginEnd = 2130903205;
        public static final int layout_goneMarginLeft = 2130903206;
        public static final int layout_goneMarginRight = 2130903207;
        public static final int layout_goneMarginStart = 2130903208;
        public static final int layout_goneMarginTop = 2130903209;
    }

    public static final class id {
        public static final int parent = 2131230799;
    }

    public static final class styleable {
        public static final int[] ConstraintLayout_Layout = new int[]{16842948, C0220R.attr.layout_constraintBaseline_creator, C0220R.attr.layout_constraintBaseline_toBaselineOf, C0220R.attr.layout_constraintBottom_creator, C0220R.attr.layout_constraintBottom_toBottomOf, C0220R.attr.layout_constraintBottom_toTopOf, C0220R.attr.layout_constraintDimensionRatio, C0220R.attr.layout_constraintEnd_toEndOf, C0220R.attr.layout_constraintEnd_toStartOf, C0220R.attr.layout_constraintGuide_begin, C0220R.attr.layout_constraintGuide_end, C0220R.attr.layout_constraintGuide_percent, C0220R.attr.layout_constraintHorizontal_bias, C0220R.attr.layout_constraintHorizontal_chainPacked, C0220R.attr.layout_constraintHorizontal_weight, C0220R.attr.layout_constraintLeft_creator, C0220R.attr.layout_constraintLeft_toLeftOf, C0220R.attr.layout_constraintLeft_toRightOf, C0220R.attr.layout_constraintRight_creator, C0220R.attr.layout_constraintRight_toLeftOf, C0220R.attr.layout_constraintRight_toRightOf, C0220R.attr.layout_constraintStart_toEndOf, C0220R.attr.layout_constraintStart_toStartOf, C0220R.attr.layout_constraintTop_creator, C0220R.attr.layout_constraintTop_toBottomOf, C0220R.attr.layout_constraintTop_toTopOf, C0220R.attr.layout_constraintVertical_bias, C0220R.attr.layout_constraintVertical_chainPacked, C0220R.attr.layout_constraintVertical_weight, C0220R.attr.layout_editor_absoluteX, C0220R.attr.layout_editor_absoluteY, C0220R.attr.layout_goneMarginBottom, C0220R.attr.layout_goneMarginEnd, C0220R.attr.layout_goneMarginLeft, C0220R.attr.layout_goneMarginRight, C0220R.attr.layout_goneMarginStart, C0220R.attr.layout_goneMarginTop};
        public static final int ConstraintLayout_Layout_android_orientation = 0;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_creator = 1;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 2;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_creator = 3;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 4;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 5;
        public static final int ConstraintLayout_Layout_layout_constraintDimensionRatio = 6;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 7;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 8;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_begin = 9;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_end = 10;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_percent = 11;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 12;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_chainPacked = 13;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 14;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_creator = 15;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 16;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 17;
        public static final int ConstraintLayout_Layout_layout_constraintRight_creator = 18;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 19;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 20;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 21;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 22;
        public static final int ConstraintLayout_Layout_layout_constraintTop_creator = 23;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 24;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 25;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_bias = 26;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_chainPacked = 27;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_weight = 28;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteX = 29;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteY = 30;
        public static final int ConstraintLayout_Layout_layout_goneMarginBottom = 31;
        public static final int ConstraintLayout_Layout_layout_goneMarginEnd = 32;
        public static final int ConstraintLayout_Layout_layout_goneMarginLeft = 33;
        public static final int ConstraintLayout_Layout_layout_goneMarginRight = 34;
        public static final int ConstraintLayout_Layout_layout_goneMarginStart = 35;
        public static final int ConstraintLayout_Layout_layout_goneMarginTop = 36;
        public static final int[] ConstraintSet = new int[]{16842948, 16842960, 16842972, 16842996, 16842997, 16842999, 16843000, 16843001, 16843002, 16843701, 16843702, C0220R.attr.layout_constraintBaseline_creator, C0220R.attr.layout_constraintBaseline_toBaselineOf, C0220R.attr.layout_constraintBottom_creator, C0220R.attr.layout_constraintBottom_toBottomOf, C0220R.attr.layout_constraintBottom_toTopOf, C0220R.attr.layout_constraintDimensionRatio, C0220R.attr.layout_constraintEnd_toEndOf, C0220R.attr.layout_constraintEnd_toStartOf, C0220R.attr.layout_constraintGuide_begin, C0220R.attr.layout_constraintGuide_end, C0220R.attr.layout_constraintGuide_percent, C0220R.attr.layout_constraintHorizontal_bias, C0220R.attr.layout_constraintHorizontal_chainPacked, C0220R.attr.layout_constraintHorizontal_weight, C0220R.attr.layout_constraintLeft_creator, C0220R.attr.layout_constraintLeft_toLeftOf, C0220R.attr.layout_constraintLeft_toRightOf, C0220R.attr.layout_constraintRight_creator, C0220R.attr.layout_constraintRight_toLeftOf, C0220R.attr.layout_constraintRight_toRightOf, C0220R.attr.layout_constraintStart_toEndOf, C0220R.attr.layout_constraintStart_toStartOf, C0220R.attr.layout_constraintTop_creator, C0220R.attr.layout_constraintTop_toBottomOf, C0220R.attr.layout_constraintTop_toTopOf, C0220R.attr.layout_constraintVertical_bias, C0220R.attr.layout_constraintVertical_chainPacked, C0220R.attr.layout_constraintVertical_weight, C0220R.attr.layout_editor_absoluteX, C0220R.attr.layout_editor_absoluteY, C0220R.attr.layout_goneMarginBottom, C0220R.attr.layout_goneMarginEnd, C0220R.attr.layout_goneMarginLeft, C0220R.attr.layout_goneMarginRight, C0220R.attr.layout_goneMarginStart, C0220R.attr.layout_goneMarginTop};
        public static final int ConstraintSet_android_id = 1;
        public static final int ConstraintSet_android_layout_height = 4;
        public static final int ConstraintSet_android_layout_marginBottom = 8;
        public static final int ConstraintSet_android_layout_marginEnd = 10;
        public static final int ConstraintSet_android_layout_marginLeft = 5;
        public static final int ConstraintSet_android_layout_marginRight = 7;
        public static final int ConstraintSet_android_layout_marginStart = 9;
        public static final int ConstraintSet_android_layout_marginTop = 6;
        public static final int ConstraintSet_android_layout_width = 3;
        public static final int ConstraintSet_android_orientation = 0;
        public static final int ConstraintSet_android_visibility = 2;
        public static final int ConstraintSet_layout_constraintBaseline_creator = 11;
        public static final int ConstraintSet_layout_constraintBaseline_toBaselineOf = 12;
        public static final int ConstraintSet_layout_constraintBottom_creator = 13;
        public static final int ConstraintSet_layout_constraintBottom_toBottomOf = 14;
        public static final int ConstraintSet_layout_constraintBottom_toTopOf = 15;
        public static final int ConstraintSet_layout_constraintDimensionRatio = 16;
        public static final int ConstraintSet_layout_constraintEnd_toEndOf = 17;
        public static final int ConstraintSet_layout_constraintEnd_toStartOf = 18;
        public static final int ConstraintSet_layout_constraintGuide_begin = 19;
        public static final int ConstraintSet_layout_constraintGuide_end = 20;
        public static final int ConstraintSet_layout_constraintGuide_percent = 21;
        public static final int ConstraintSet_layout_constraintHorizontal_bias = 22;
        public static final int ConstraintSet_layout_constraintHorizontal_chainPacked = 23;
        public static final int ConstraintSet_layout_constraintHorizontal_weight = 24;
        public static final int ConstraintSet_layout_constraintLeft_creator = 25;
        public static final int ConstraintSet_layout_constraintLeft_toLeftOf = 26;
        public static final int ConstraintSet_layout_constraintLeft_toRightOf = 27;
        public static final int ConstraintSet_layout_constraintRight_creator = 28;
        public static final int ConstraintSet_layout_constraintRight_toLeftOf = 29;
        public static final int ConstraintSet_layout_constraintRight_toRightOf = 30;
        public static final int ConstraintSet_layout_constraintStart_toEndOf = 31;
        public static final int ConstraintSet_layout_constraintStart_toStartOf = 32;
        public static final int ConstraintSet_layout_constraintTop_creator = 33;
        public static final int ConstraintSet_layout_constraintTop_toBottomOf = 34;
        public static final int ConstraintSet_layout_constraintTop_toTopOf = 35;
        public static final int ConstraintSet_layout_constraintVertical_bias = 36;
        public static final int ConstraintSet_layout_constraintVertical_chainPacked = 37;
        public static final int ConstraintSet_layout_constraintVertical_weight = 38;
        public static final int ConstraintSet_layout_editor_absoluteX = 39;
        public static final int ConstraintSet_layout_editor_absoluteY = 40;
        public static final int ConstraintSet_layout_goneMarginBottom = 41;
        public static final int ConstraintSet_layout_goneMarginEnd = 42;
        public static final int ConstraintSet_layout_goneMarginLeft = 43;
        public static final int ConstraintSet_layout_goneMarginRight = 44;
        public static final int ConstraintSet_layout_goneMarginStart = 45;
        public static final int ConstraintSet_layout_goneMarginTop = 46;
        public static final int[] LinearConstraintLayout = new int[]{16842948};
        public static final int LinearConstraintLayout_android_orientation = 0;
    }
}
